import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { useToast } from "../../../app/providers/ToastProvider";
import { Button } from "../../../components/ui/button";
import { APP_ROUTES } from "../../../lib/constants";
import { getApiErrorMessage } from "../../../lib/apiError";
import { barcodeService } from "../services/barcodeService";

export function BarcodesDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const toast = useToast();
  const detailQuery = useQuery({
    queryKey: ["barcode", id],
    queryFn: () => barcodeService.getBarcode(id ?? ""),
    enabled: typeof id === "string" && id.length > 0,
  });

  const regenerate = useMutation({
    mutationFn: barcodeService.regenerate,
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["barcode", id] });
      await queryClient.invalidateQueries({ queryKey: ["barcodes"] });
      toast.success("Barcode berhasil diregenerate.");
    },
    onError: (error) => {
      toast.error(getApiErrorMessage(error, "Gagal regenerate barcode."));
    },
  });

  const deactivate = useMutation({
    mutationFn: barcodeService.deactivate,
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["barcode", id] });
      await queryClient.invalidateQueries({ queryKey: ["barcodes"] });
      toast.success("Barcode berhasil dinonaktifkan.");
    },
    onError: (error) => {
      toast.error(getApiErrorMessage(error, "Gagal menonaktifkan barcode."));
    },
  });

  const remove = useMutation({
    mutationFn: barcodeService.remove,
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["barcodes"] });
      toast.success("Barcode berhasil dihapus.");
      navigate(APP_ROUTES.barcodes);
    },
    onError: (error) => {
      toast.error(getApiErrorMessage(error, "Gagal menghapus barcode."));
    },
  });

  const barcode = detailQuery.data;

  if (detailQuery.isLoading) {
    return <p className="text-sm text-muted-foreground">Loading barcode detail...</p>;
  }

  return (
    <section className="space-y-6">
      <h1 className="text-2xl font-semibold">Barcode Detail</h1>

      <section className="rounded-2xl border border-border bg-card p-5 text-sm">
        <div className="grid gap-3 md:grid-cols-2">
          <p><span className="text-muted-foreground">Employee Name:</span> {barcode?.employee_name ?? "-"}</p>
          <p><span className="text-muted-foreground">Employee Code:</span> {barcode?.employee_code ?? "-"}</p>
          <p><span className="text-muted-foreground">Barcode Value:</span> {barcode?.code ?? "-"}</p>
          <p><span className="text-muted-foreground">Type:</span> {barcode?.type ?? "-"}</p>
          <p><span className="text-muted-foreground">Status:</span> {barcode?.is_active ? "Active" : "Inactive"}</p>
          <p><span className="text-muted-foreground">Created Date:</span> {barcode?.generated_at?.slice(0, 10) ?? "-"}</p>
          <p><span className="text-muted-foreground">Generated By:</span> {barcode?.generated_by_name ?? "-"}</p>
        </div>
        <div className="mt-4 flex min-h-36 items-center justify-center rounded-xl border border-dashed border-border p-4">
          {barcode?.qr_image_data_url ? (
            <img src={barcode.qr_image_data_url} alt={`Barcode ${barcode.code}`} className="h-44 w-44 rounded-lg bg-white p-2" />
          ) : (
            <p className="text-muted-foreground">Barcode image unavailable</p>
          )}
        </div>
      </section>

      <div className="flex flex-wrap gap-3">
        <Button onClick={() => id && regenerate.mutate(id)}>Regenerate Barcode</Button>
        <Button variant="outline" onClick={() => id && deactivate.mutate(id)}>Deactivate Barcode</Button>
        <Button variant="outline" onClick={() => id && remove.mutate(id)}>Delete Barcode</Button>
        <Button variant="outline" onClick={() => navigate(APP_ROUTES.barcodes)}>Back</Button>
      </div>
    </section>
  );
}
